### ISSUE TITLE
Test Cases + Data Model/Controller Implementation

### ISSUE THREAD

**Issue by vanbelle** [CMPUT301W15T12/C301Project#42]
- [ ] Claim Class - Jim
- [ ] Expense Class - Raymond
- [ ] ExpenseList Class - Raymond
- [ ] Destination Class  - Megan
- [ ] User Class - Omar
- [ ] UserList Class - Omar
- [ ] ClaimList Data Model - Jim
- [ ] ClaimList Controller - Jim
- [ ] ClaimList Manager - Jim
- [ ] User List Controller - Omar
- [ ] User List Manager - Omar

**Comment by IchigoKIl** [comment]
Some suggestions/questions about ClaimList:

Instead of using getUserClaims, getFiltered and getSubmittedClaims to return a new ArrayList after every call (which could be tedious/inefficient for updating a list view) I suggest we make a generic filter method that takes in the arraylist to be modified, username, status and tags to filter, and it will clear the arraylist and add from the claims arraylist claims that satisfy the filter conditions.

What is the reason for having returnClaim and approveClaim? Shouldn't that be handled by the controller? 

Should we really have a condition that a claim name should be unique for addClaim? And even so why would removeClaim take in a claim name and not a claim to be removed, since it claim should already be known if claim name were to be extracted?

**Comment by vanbelle** [comment]
I think that sounds good, except that since claims are never filtered by both users/tags and status, what if we just split them in two functions? One that filters claims by user/tags and one that filters by Submitted status? Either way there is only one call and shouldnt be too bad for a listview. also The filter method would simpler.

**Comment by qsjiang** [comment]
Hey Raymond, just a head up. 

I am going to take over ClaimList.java

**Comment by IchigoKIl** [comment]
I have already worked on new ClaimList2, ExpenseList, and List classes and have just pushed it onto git. We can look over the implementation during the meeting today and see if there are any issues, but if not I think we should just use what is done and I'll just add any missing pieces in the next couple of days.

**Comment by qsjiang** [comment]
There are some major issues inside the ClaimList.java.
I took a look at the new code some of those issues still exist.

I have written everything done, was planning to show you during the meeting.
//1. use this.var and ClassName.var
//Why? Can you spot what's wrong with getUserClaims?
	public class ClaimList implements List<Claim>{
		private static ArrayList<Claim> claims;
		private static ArrayList<Listener> listeners;
		private static int counter;
		
		public ArrayList<Claim> getUserClaims(String Username) {
			ArrayList<Claim> claims = new ArrayList<Claim>();
			for (int i = 0; i < claims.size(); i++) {
				if (claims.get(i).getClaimant().getUserName().equals(Username)) {
					claims.add(claims.get(i));
				}
			}
			return claims;
		}
	...

//2. problem with getter and setter.
//not all variables need a getter and setter
	public int getCounter(){
		return counter;
	}
		
	public void setCounter(int id_counter){
		counter = id_counter;
	}



//3. pass user object instead of String Username
//WHy!?   You can redefined the meaning of equals later.
	public ArrayList<Claim> getUserClaims(String Username) {
		...
	}

**Comment by qsjiang** [comment]
Your effort is not going to go be wasted, I am going to build on top of your code instead of start over, but I have to take it over from here.

**Comment by Pengwin-man** [comment]
Jim.  Dont take over.  If you have an issue we can talk about it during the meeting.  This is not the way to go about it.  and WHY would you use a string to find a user?  That does not even make sense.  Just wait and lets talk about it during the meeting.

**Comment by qsjiang** [comment]
Omar. What I posted is not mine code. These are the problems I have seen in the current ClaimList.java

**Comment by qsjiang** [comment]
ClaimList.java was assigned to me orginaly

**Comment by IchigoKIl** [comment]
I don't believe you are looking at the right code. I pushed a new ClaimList2 which extends List2 and uses a singleton pattern.

**Comment by qsjiang** [comment]
yes I saw it.  there are still some problems with the getter and setter

**Comment by qsjiang** [comment]
but that doesn't matter.   the reason I need to work on the claimlist.java is simply because it is closely coupled with my code, and it makes more sense to reassigned the responsibility
